<?php

/**
 * Implements hook_menu().
 */
function dbtng_migrator_menu() {
  $items = array();  

  $items['admin/structure/dbtng/migrator'] = array(
    'title' => 'Migrator',
    'description' => 'Use the power of DBTNG to migrate a database.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dbtng_migrator_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}  

/**
 * Form function, called by drupal_get_form()
 * in dbtng_migrator_menu().
 */
function dbtng_migrator_settings($form, &$form_state) {
  $form['description']['#markup'] = t('Below are the database connections defined in Drupal. You can use this interface to migrate database to another assuming it is a Drupal database.');
  global $databases;
  foreach (array_keys($databases) as $key) {
    $connection_info = Database::getConnectionInfo($key);
    $info = $connection_info['default'];
    $rows[] = array($key, $info['driver'], $info['database']);
    $options[$key] = $key;
  }
  $headers = array('Key', 'Driver', 'Database');
  $form['databases']['#markup'] = theme('table', array('header' => $headers, 'rows' => $rows));
  $form['migrate_origin'] = array(
    '#title' => 'Origin Database',
    '#type' => 'select',
    '#options' => $options,
    '#description' => t('The database the data will be replicated from.'),
  );
  $form['migrate_destination'] = array(
    '#title' => 'Destination Database',
    '#type' => 'select',
    '#options' => $options,
    '#description' => t('The database the origin data will be replicated too.'),
  );
  $form['migrate_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Migrate'),
  );
  return $form;
}

/**
 * Validation handler for form dbtng_migrator_settings.
 */
function dbtng_migrator_settings_validate($form, $form_state) {
  if ($form_state['values']['migrate_destination'] == $form_state['values']['migrate_origin']) {
    form_set_error('migrate_destination', t('Migration origin cannot be the same as the destination.'));
    return;
  }

  $origin = $form_state['values']['migrate_origin'];
  $dest   = $form_state['values']['migrate_destination'];

  // Connect to the origin and generate a list of tables in the database.
  db_set_active($origin);
  $modules = module_list(TRUE);
  $tables  = array();
  foreach ($modules as $module) {
    $schema = drupal_get_schema_unprocessed($module);
    _drupal_schema_initialize($schema, $module, TRUE);

    // Some modules won't actually have a schema.
    if (!is_array($schema)) {
      continue;
    }
    foreach ($schema as $table => $info) {
      $tables[] = $table;
    }
  }

  // Check that those tables don't already exists in the destination.
  db_set_active($dest);
  foreach ($tables as $table) {
    if (db_table_exists($table)) {
      form_set_error('migrate_destination', t('%table already exists in destination database. DBTNG Migrator will not override existing data', array('%table' => $table)));
    }
  }
  db_set_active('default');
}

/**
 * Submission handler for form dbtng_migrator_settings.
 */
function dbtng_migrator_settings_submit($form, $form_state) {
  $batch = array(
    'title' => t("Replicating Database"),
    'operations' => array(
      array('dbtng_migrator_batch_install_schema', array($form_state['values']['migrate_origin'], $form_state['values']['migrate_destination'])),
      array('dbtng_migrator_batch_migrate_table', array($form_state['values']['migrate_origin'], $form_state['values']['migrate_destination'])),
    ),
    'finished' => 'dbtng_migrator_batch_report',
    'file' => drupal_get_path('module', 'dbtng_migrator') . '/dbtng_migrator.batch.inc',
  );
  batch_set($batch);
}
